// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdw875Lcft9mkwZQmjEL1NN5cqxQiGWcE',
    appId: '1:872814823547:web:579da5fee6899f61b23ade',
    messagingSenderId: '872814823547',
    projectId: 'dietbuddy-fa395',
    authDomain: 'dietbuddy-fa395.firebaseapp.com',
    storageBucket: 'dietbuddy-fa395.firebasestorage.app',
    measurementId: 'G-LC67SLMGEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBORfhsOPIfquEkfy30FzZLUzx-r_1l21k',
    appId: '1:872814823547:android:cbbb9bcbfab327d8b23ade',
    messagingSenderId: '872814823547',
    projectId: 'dietbuddy-fa395',
    storageBucket: 'dietbuddy-fa395.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCSxvQM8is_FcYhf_6CPPNOqXLlHCGE2k',
    appId: '1:872814823547:ios:29005c4444e9d749b23ade',
    messagingSenderId: '872814823547',
    projectId: 'dietbuddy-fa395',
    storageBucket: 'dietbuddy-fa395.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCSxvQM8is_FcYhf_6CPPNOqXLlHCGE2k',
    appId: '1:872814823547:ios:29005c4444e9d749b23ade',
    messagingSenderId: '872814823547',
    projectId: 'dietbuddy-fa395',
    storageBucket: 'dietbuddy-fa395.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdw875Lcft9mkwZQmjEL1NN5cqxQiGWcE',
    appId: '1:872814823547:web:c8faced618697e9cb23ade',
    messagingSenderId: '872814823547',
    projectId: 'dietbuddy-fa395',
    authDomain: 'dietbuddy-fa395.firebaseapp.com',
    storageBucket: 'dietbuddy-fa395.firebasestorage.app',
    measurementId: 'G-PYYFWPLPD6',
  );
}
